### ISSUE TITLE
Failed to compile on build

### ISSUE THREAD

**Issue by shanebenlolo** [OHIF/react-vtkjs-viewport#146]
met with the following error on build: 

```
ERROR in ./node_modules/vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker.js
Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
ValidationError: Worker Loader Invalid Options

options.inline should be boolean

    at validateOptions (/mnt/c/Users/ShaneBenlolo/react-vtkjs-viewport/node_modules/worker-loader/node_modules/schema-utils/src/validateOptions.js:31:11)
    at Object.pitch (/mnt/c/Users/ShaneBenlolo/react-vtkjs-viewport/node_modules/worker-loader/dist/index.js:57:29)
 @ ./node_modules/vtk.js/Sources/Filters/General/PaintFilter/index.js 8:0-94 42:21-38
 @ ./src/VTKViewport/View3D.js
 @ ./src/index.js
 @ ./examples/VTKLoadImageDataExample.js
 @ ./examples/App.js
 @ ./examples/index.js
```

Steps to reproduce:
```
git clone https://github.com/OHIF/react-vtkjs-viewport.git
cd react-vtkjs-viewport/
yarn add react-vtkjs-viewport vtk.js
yarn install
yarn run dev
```

issue can be fixed by editing `/react-vtkjs-viewport/node_modules/worker-loader/dist/options.json`, line 8 to `"type": "string"` rather than `"type": "boolean"`. 

However, when I get it to compile after making that adjustment, none of the examples work. What is going on here? I want to check out the fusion example. When I click the fusion example, I'm met with the following error: 

```
Uncaught (in promise) TypeError: Cannot read property 'render' of undefined
    at VTKFusionExample.js:481
    at Array.forEach (<anonymous>)
    at VTKFusionExample.rerenderAll (VTKFusionExample.js:476)
    at onPixelDataInsertedCallback (VTKFusionExample.js:351)
    at getImageData.js:78
    at Array.forEach (<anonymous>)
    at Object._publishPixelDataInserted (getImageData.js:77)
    at insertPixelData (loadImageData.js:102)
    at cornerstoneTools.js:10001
```
all other examples have different errors and are not working.

**Comment by shanebenlolo** [comment]
Tried cloning this repo again and it seems to be working now. Thank you!
